puts "🌍 Seeding locations..."
locations = [
  {
      id: '0f4a91ea-7cbe-411a-842d-125e234df807',
      name: 'Orestiada Hotel',
      description: 'Authentic Albanian filming location in Berat. Hotel/Guesthouse perfect for film and photo productions.',
      location_type: 'Hotels & Guesthouses',
      city: 'Berat',
      county: 'Berat',
      address: 'Bulevardi Republika, Berat 5001',
      latitude: 40.71043,
      longitude: 19.949058,
      price_per_hour: 1320,
      price_per_day: 7920,
      capacity: 40,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Berat_Orestiada Hotel.jpg',
      images: ['/locations/orestiada-hotel/photo-1.jpg', '/locations/orestiada-hotel/photo-2.jpg', '/locations/orestiada-hotel/photo-3.jpg', '/locations/orestiada-hotel/photo-4.jpg', '/locations/orestiada-hotel/photo-5.jpg', '/locations/orestiada-hotel/photo-6.jpg'],
      available: true,
      host_name: 'Skauter Team',
      host_verified: true,
  },
  {
      id: '28aa3a23-96c0-4200-9234-b4d02463a593',
      name: 'Vila Balliu',
      description: 'Authentic Albanian filming location in Berat. Villa/Estate perfect for film and photo productions.',
      location_type: 'Villas & Estates',
      city: 'Berat',
      county: 'Berat',
      address: 'Lagjja Mangalem, Rruga Mihal Komnena, Berat',
      latitude: 40.705279,
      longitude: 19.951633,
      price_per_hour: 2200,
      price_per_day: 13200,
      capacity: 75,
      tags: ['Luxury', 'Residential', 'Garden'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Berat_Vila Balliu.jpg',
      images: ['/locations/vila-balliu/photo-1.jpg', '/locations/vila-balliu/photo-2.jpg', '/locations/vila-balliu/photo-3.jpg', '/locations/vila-balliu/photo-4.jpg', '/locations/vila-balliu/photo-5.jpg', '/locations/vila-balliu/photo-6.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'f07bf232-24b7-482a-8f94-293766f6b8d6',
      name: 'Vila Mishel',
      description: 'Authentic Albanian filming location in Berat. Villa/Estate perfect for film and photo productions.',
      location_type: 'Villas & Estates',
      city: 'Berat',
      county: 'Berat',
      address: 'Lagjja Gorica, Rruga Nikolla Buhuri, Berat',
      latitude: 40.710242,
      longitude: 19.948106,
      price_per_hour: 2200,
      price_per_day: 13200,
      capacity: 30,
      tags: ['Luxury', 'Residential', 'Garden'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Berat_Vila Mishel.jpg',
      images: ['/locations/vila-mishel/photo-1.jpg', '/locations/vila-mishel/photo-2.jpg', '/locations/vila-mishel/photo-3.jpg', '/locations/vila-mishel/photo-4.jpg', '/locations/vila-mishel/photo-5.jpg', '/locations/vila-mishel/photo-6.jpg', '/locations/vila-mishel/photo-7.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '4104cda8-fb22-406a-b88a-9c2a02d228a5',
      name: 'Old metal factory',
      description: 'Authentic Albanian filming location in Elbasan. Industrial Space perfect for film and photo productions.',
      location_type: 'Industrial Spaces',
      city: 'Elbasan',
      county: 'Elbasan',
      address: 'Altes Fabrikgelände, Bradashesh, Elbasan',
      latitude: 41.108149,
      longitude: 20.085928,
      price_per_hour: 1800,
      price_per_day: 10800,
      capacity: 30,
      tags: ['Urban', 'Industrial', 'Modern'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Elbasan city_Old metal factory.png',
      images: ['/locations/Elbasan city_Old metal factory.png'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'bc84c6a2-e202-4de2-929f-c9e755e6e14d',
      name: 'BASKETBALL ARENA',
      description: 'Authentic Albanian filming location in Elbasan. Sports Facility perfect for film and photo productions.',
      location_type: 'Sports Facilities',
      city: 'Elbasan',
      county: 'Elbasan',
      address: 'Rruga Kozma Naska, Elbasan 3001',
      latitude: 41.109357,
      longitude: 20.081484,
      price_per_hour: 1800,
      price_per_day: 10800,
      capacity: 40,
      tags: ['Modern', 'Sports', 'Events'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/ELBASAN_BASKETBALL ARENA.jpg',
      images: ['/locations/basketball-arena/photo-1.jpg', '/locations/basketball-arena/photo-2.jpg', '/locations/basketball-arena/photo-3.jpg', '/locations/basketball-arena/photo-4.jpg', '/locations/basketball-arena/photo-5.jpg', '/locations/basketball-arena/photo-6.jpg', '/locations/basketball-arena/photo-7.jpg', '/locations/basketball-arena/photo-8.jpg', '/locations/basketball-arena/photo-9.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '995df170-3c0d-4dd5-9f75-3b8f47173daf',
      name: 'Central Park',
      description: 'Authentic Albanian filming location in Elbasan. Park/Garden perfect for film and photo productions.',
      location_type: 'Parks & Gardens',
      city: 'Elbasan',
      county: 'Elbasan',
      address: 'Rruga Lef Nosi, Elbasan 3001',
      latitude: 41.108428,
      longitude: 20.077351,
      price_per_hour: 1000,
      price_per_day: 6000,
      capacity: 40,
      tags: ['Nature', 'Outdoor', 'Park'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Elbasan_Central Park.jpg',
      images: ['/locations/central-park/photo-1.jpg', '/locations/central-park/photo-2.jpg', '/locations/central-park/photo-3.jpg', '/locations/central-park/photo-4.jpg', '/locations/central-park/photo-5.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '132b22b4-b0d0-46e8-b0f5-cec3afdb5a57',
      name: 'Bujtina Qosja',
      description: 'Authentic Albanian filming location in Gjinar, Elbasan. Hotel/Guesthouse perfect for film and photo productions.',
      location_type: 'Hotels & Guesthouses',
      city: 'Gjinar, Elbasan',
      county: 'Elbasan',
      address: 'Fshati Gjinar, Elbasan 3000',
      latitude: 41.081492,
      longitude: 20.142023,
      price_per_hour: 1200,
      price_per_day: 7200,
      capacity: 40,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Elbasan_Gjinar_Bujtina Qosja.jpg',
      images: ['/locations/Elbasan_Gjinar_Bujtina Qosja.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'e5bbe234-9e03-4b61-9fd8-7f505d62127e',
      name: 'Bujtina Skenderi',
      description: 'Authentic Albanian filming location in Gjinar, Elbasan. Hotel/Guesthouse perfect for film and photo productions.',
      location_type: 'Hotels & Guesthouses',
      city: 'Gjinar, Elbasan',
      county: 'Elbasan',
      address: 'Fshati Gjinar, Elbasan 3014',
      latitude: 41.07444,
      longitude: 20.142823,
      price_per_hour: 1200,
      price_per_day: 7200,
      capacity: 100,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Elbasan_Gjinar_Bujtina Skenderi.jpg',
      images: ['/locations/Elbasan_Gjinar_Bujtina Skenderi.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '11087676-f526-44d6-9ecb-2f07c2d3ef7f',
      name: 'Bujtina Skenderi 2',
      description: 'Authentic Albanian filming location in Gjinar, Elbasan. Hotel/Guesthouse perfect for film and photo productions.',
      location_type: 'Hotels & Guesthouses',
      city: 'Gjinar, Elbasan',
      county: 'Elbasan',
      address: 'Fshati Gjinar, Elbasan 3014',
      latitude: 41.076041,
      longitude: 20.14747,
      price_per_hour: 1200,
      price_per_day: 7200,
      capacity: 15,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Elbasan_Gjinar_Bujtina Skenderi 2.jpg',
      images: ['/locations/Elbasan_Gjinar_Bujtina Skenderi 2.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '463e32cd-54cd-4bb5-b869-e4c70e63d812',
      name: 'Ëndrra',
      description: 'Authentic Albanian filming location in Gjinar, Elbasan. Unique Location perfect for film and photo productions.',
      location_type: 'Unique Spaces',
      city: 'Gjinar, Elbasan',
      county: 'Elbasan',
      address: 'Fshati Gjinar, Elbasan',
      latitude: 41.082739,
      longitude: 20.142098,
      price_per_hour: 1200,
      price_per_day: 7200,
      capacity: 20,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Elbasan_Gjinar_E╠êndrra.jpg',
      images: ['/locations/Elbasan_Gjinar_E╠êndrra.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'c0adb898-7f13-47ec-ba66-3268c4055875',
      name: 'Restorant 3 Bujtinat',
      description: 'Authentic Albanian filming location in Gjinar, Elbasan. Hotel/Guesthouse perfect for film and photo productions.',
      location_type: 'Hotels & Guesthouses',
      city: 'Gjinar, Elbasan',
      county: 'Elbasan',
      address: 'Rruga Gjinar-Elbasan Km 1, Fshati Gjinar',
      latitude: 41.078806,
      longitude: 20.144944,
      price_per_hour: 1200,
      price_per_day: 7200,
      capacity: 20,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Elbasan_Gjinar_Restorant 3 Bujtinat.jpg',
      images: ['/locations/Elbasan_Gjinar_Restorant 3 Bujtinat.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'aa804c53-907e-48c3-b0a1-186eae3c3896',
      name: 'Vila',
      description: 'Authentic Albanian filming location in Gjinar, Elbasan. Villa/Estate perfect for film and photo productions.',
      location_type: 'Villas & Estates',
      city: 'Gjinar, Elbasan',
      county: 'Elbasan',
      address: 'Fshati Gjinar, Elbasan',
      latitude: 41.075397,
      longitude: 20.14533,
      price_per_hour: 2000,
      price_per_day: 12000,
      capacity: 25,
      tags: ['Luxury', 'Residential', 'Garden'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Elbasan_Gjinar_Vila.jpg',
      images: ['/locations/Elbasan_Gjinar_Vila.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'b2091b9d-19a7-4b04-a9bf-8c3caa2951a8',
      name: 'Wooden Vila',
      description: 'Authentic Albanian filming location in Gjinar, Elbasan. Villa/Estate perfect for film and photo productions.',
      location_type: 'Villas & Estates',
      city: 'Gjinar, Elbasan',
      county: 'Elbasan',
      address: 'Fshati Gjinar, Elbasan',
      latitude: 41.081673,
      longitude: 20.149244,
      price_per_hour: 2000,
      price_per_day: 12000,
      capacity: 20,
      tags: ['Luxury', 'Residential', 'Garden'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Elbasan_Gjinar_Wooden Vila.jpg',
      images: ['/locations/Elbasan_Gjinar_Wooden Vila.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '394d1853-e3be-41b1-9da0-97a8305b90e3',
      name: 'Guri Hotel',
      description: 'Authentic Albanian filming location in Elbasan. Hotel/Guesthouse perfect for film and photo productions.',
      location_type: 'Hotels & Guesthouses',
      city: 'Elbasan',
      county: 'Elbasan',
      address: 'Rruga Rinia, Elbasan',
      latitude: 41.108952,
      longitude: 20.08047,
      price_per_hour: 1200,
      price_per_day: 7200,
      capacity: 20,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Elbasan_Guri Hotel.jpg',
      images: ['/locations/guri-hotel/photo-1.jpg', '/locations/guri-hotel/photo-2.jpg', '/locations/guri-hotel/photo-3.jpg', '/locations/guri-hotel/photo-4.jpg', '/locations/guri-hotel/photo-5.jpg', '/locations/guri-hotel/photo-6.jpg', '/locations/guri-hotel/photo-7.jpg', '/locations/guri-hotel/photo-8.jpg', '/locations/guri-hotel/photo-9.jpg', '/locations/guri-hotel/photo-10.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '52b2b8b0-fa08-491f-bd11-0052bf7b3022',
      name: 'Kamare Bridge',
      description: 'Authentic Albanian filming location in Mirake, Elbasan. Bridge/Infrastructure perfect for film and photo productions.',
      location_type: 'Bridges',
      city: 'Mirake, Elbasan',
      county: 'Elbasan',
      address: 'Mirakë, Librazhd (Old road near Shkumbin River)',
      latitude: 41.035967,
      longitude: 20.38792,
      price_per_hour: 800,
      price_per_day: 4800,
      capacity: 75,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Elbasan_Mirake_Kamare Bridge.jpg',
      images: ['/locations/Elbasan_Mirake_Kamare Bridge.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'c8bdf6c3-c129-4268-9fc7-1aee24856aa4',
      name: 'Old Castle Neighbourhood',
      description: 'Authentic Albanian filming location in Elbasan. Historic Castle perfect for film and photo productions.',
      location_type: 'Historic Castles',
      city: 'Elbasan',
      county: 'Elbasan',
      address: 'Lagjja Kala, Elbasan',
      latitude: 41.115362,
      longitude: 20.085136,
      price_per_hour: 2500,
      price_per_day: 15000,
      capacity: 20,
      tags: ['Historic', 'Castle', 'Medieval'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Elbasan_Old Castle Neighbourhood.jpg',
      images: ['/locations/Elbasan_Old Castle Neighbourhood.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'b5cbe860-d326-4266-9cb2-cb1ead9ec0d7',
      name: 'Old train Station',
      description: 'Authentic Albanian filming location in Elbasan. Transportation Hub perfect for film and photo productions.',
      location_type: 'Unique Spaces',
      city: 'Elbasan',
      county: 'Elbasan',
      address: 'Rruga e Trenit, Elbasan (Terminus near city center)',
      latitude: 41.108702,
      longitude: 20.080505,
      price_per_hour: 900,
      price_per_day: 5400,
      capacity: 30,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Elbasan_Old train Station.jpg',
      images: ['/locations/Elbasan_Old train Station.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'd11c50f6-c682-4291-be8e-f65420ae44bd',
      name: 'Olive Oil Factory',
      description: 'Authentic Albanian filming location in Elbasan. Industrial Space perfect for film and photo productions.',
      location_type: 'Industrial Spaces',
      city: 'Elbasan',
      county: 'Elbasan',
      address: 'Fabrika e Vajit, Elbasan',
      latitude: 41.113813,
      longitude: 20.080929,
      price_per_hour: 1800,
      price_per_day: 10800,
      capacity: 40,
      tags: ['Urban', 'Industrial', 'Modern'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Elbasan_Olive Oil Factory.jpg',
      images: ['/locations/olive-oil-factory/photo-1.jpg', '/locations/olive-oil-factory/photo-2.jpg', '/locations/olive-oil-factory/photo-3.jpg', '/locations/olive-oil-factory/photo-4.jpg', '/locations/olive-oil-factory/photo-5.jpg', '/locations/olive-oil-factory/photo-6.jpg', '/locations/olive-oil-factory/photo-7.jpg', '/locations/olive-oil-factory/photo-8.jpg', '/locations/olive-oil-factory/photo-9.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '7517fe36-ee21-4b1d-a6c8-9fd914f3a7c3',
      name: 'Vila Eden',
      description: 'Authentic Albanian filming location in Korçë. Villa/Estate perfect for film and photo productions.',
      location_type: 'Villas & Estates',
      city: 'Korçë',
      county: 'Korçë',
      address: 'Rruga Themistokli Gërmenji, Korçë',
      latitude: 40.61581,
      longitude: 20.77864,
      price_per_hour: 2000,
      price_per_day: 12000,
      capacity: 40,
      tags: ['Luxury', 'Residential', 'Garden'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Korc╠ºa_Vila Eden.jpg',
      images: ['/locations/Korc╠ºa_Vila Eden.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'b7baac92-bfc6-4237-9d48-9d54d83922ef',
      name: 'Castle',
      description: 'Authentic Albanian filming location in Krujë. Historic Castle perfect for film and photo productions.',
      location_type: 'Historic Castles',
      city: 'Krujë',
      county: 'Krujë',
      address: 'Rruga Kala, Krujë',
      latitude: 41.511328,
      longitude: 19.79716,
      price_per_hour: 2500,
      price_per_day: 15000,
      capacity: 75,
      tags: ['Historic', 'Castle', 'Medieval'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Kruja_Castle.jpg',
      images: ['/locations/Kruja_Castle.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'a0eef7d6-a4b9-4d9a-ae9d-c53e6a5634bb',
      name: 'Old Bazaar',
      description: 'Authentic Albanian filming location in Krujë. Market/Bazaar perfect for film and photo productions.',
      location_type: 'Markets & Bazaars',
      city: 'Krujë',
      county: 'Krujë',
      address: 'Rruga Pazari i Vjetër, Krujë',
      latitude: 41.513026,
      longitude: 19.797073,
      price_per_hour: 1200,
      price_per_day: 7200,
      capacity: 30,
      tags: ['Historic', 'Urban', 'Cultural'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Kruja_Old Bazaar.jpg',
      images: ['/locations/old-bazaar/photo-1.jpg', '/locations/old-bazaar/photo-2.jpg', '/locations/old-bazaar/photo-3.jpg', '/locations/old-bazaar/photo-4.jpg', '/locations/old-bazaar/photo-5.jpg', '/locations/old-bazaar/photo-6.jpg', '/locations/old-bazaar/photo-7.jpg', '/locations/old-bazaar/photo-8.jpg', '/locations/old-bazaar/photo-9.jpg', '/locations/old-bazaar/photo-10.jpg', '/locations/old-bazaar/photo-11.jpg', '/locations/old-bazaar/photo-12.jpg', '/locations/old-bazaar/photo-13.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'f9d0b9d2-8f34-4251-a338-ba87a287e5bc',
      name: 'Drilon Lake',
      description: 'Authentic Albanian filming location in Pogradec. Waterfront perfect for film and photo productions.',
      location_type: 'Waterfront & Lakes',
      city: 'Pogradec',
      county: 'Pogradec',
      address: 'Drilon National Park, Tushemisht, Pogradec',
      latitude: 40.898044,
      longitude: 20.650594,
      price_per_hour: 1500,
      price_per_day: 9000,
      capacity: 50,
      tags: ['Coastal', 'Water', 'Scenic', 'Beach'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Pogradec_Drilon Lake.jpg',
      images: ['/locations/Pogradec_Drilon Lake.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '9a37b8b3-d55c-42f4-a93b-6202988090dc',
      name: 'House 1960',
      description: 'Authentic Albanian filming location in Lin, Pogradec. Villa/Estate perfect for film and photo productions.',
      location_type: 'Villas & Estates',
      city: 'Lin, Pogradec',
      county: 'Pogradec',
      address: 'Rruga e Linit, Fshati Lin, Pogradec',
      latitude: 40.921945,
      longitude: 20.671599,
      price_per_hour: 2000,
      price_per_day: 12000,
      capacity: 25,
      tags: ['Luxury', 'Residential', 'Garden'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Pogradec_Lin_House 1960.jpg',
      images: ['/locations/Pogradec_Lin_House 1960.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '6ac6da41-dbf9-47be-8ea4-2b6a7cc5a409',
      name: 'Ollga',
      description: 'Authentic Albanian filming location in Tushemisht, Pogradec. Unique Location perfect for film and photo productions.',
      location_type: 'Unique Spaces',
      city: 'Tushemisht, Pogradec',
      county: 'Pogradec',
      address: 'Tushemisht Center (Statue of \"Ollga\"), Pogradec',
      latitude: 40.935469,
      longitude: 20.648182,
      price_per_hour: 1200,
      price_per_day: 7200,
      capacity: 100,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Pogradec_Tushemisht_Ollga.jpg',
      images: ['/locations/Pogradec_Tushemisht_Ollga.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '27c89613-6269-453a-874e-6c50e0e400ed',
      name: 'Abandoned Factory',
      description: 'Authentic Albanian filming location in Prrenjas. Industrial Space perfect for film and photo productions.',
      location_type: 'Industrial Spaces',
      city: 'Prrenjas',
      county: 'Prrenjas',
      address: 'Lagjja e Re (Lady Bug Buildings), Prrenjas',
      latitude: 41.051378,
      longitude: 20.593053,
      price_per_hour: 1800,
      price_per_day: 10800,
      capacity: 50,
      tags: ['Urban', 'Industrial', 'Modern', 'Communist Era'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Prrenjas_Abandoned Factory.jpg',
      images: ['/locations/abandoned-factory/photo-1.jpg', '/locations/abandoned-factory/photo-2.jpg', '/locations/abandoned-factory/photo-3.jpg', '/locations/abandoned-factory/photo-4.jpg', '/locations/abandoned-factory/photo-5.jpg', '/locations/abandoned-factory/photo-6.jpg', '/locations/abandoned-factory/photo-7.jpg', '/locations/abandoned-factory/photo-8.jpg', '/locations/abandoned-factory/photo-9.jpg', '/locations/abandoned-factory/photo-10.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '23450924-dc05-4aa0-b454-0eb8eaed453c',
      name: 'Bicycle Bar Museum',
      description: 'Authentic Albanian filming location in Shkodër. Museum/Gallery perfect for film and photo productions.',
      location_type: 'Cultural Venues',
      city: 'Shkodër',
      county: 'Shkodër',
      address: 'Rruga Kolë Idromeno (Pedonalja), Shkodër',
      latitude: 42.068939,
      longitude: 19.506808,
      price_per_hour: 1500,
      price_per_day: 9000,
      capacity: 30,
      tags: ['Cultural', 'Art', 'Educational'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Shkodra_Bicycle Bar Museum.jpg',
      images: ['/locations/bicycle-bar-museum/photo-1.jpg', '/locations/bicycle-bar-museum/photo-2.jpg', '/locations/bicycle-bar-museum/photo-3.jpg', '/locations/bicycle-bar-museum/photo-4.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '9742a8b7-0698-470b-aef7-3c8922f4e047',
      name: 'Mask Factory',
      description: 'Authentic Albanian filming location in Shkodër. Industrial Space perfect for film and photo productions.',
      location_type: 'Industrial Spaces',
      city: 'Shkodër',
      county: 'Shkodër',
      address: 'Rruga Inxh. Gjovalin Gjadri, Shkodër',
      latitude: 42.070698,
      longitude: 19.506861,
      price_per_hour: 1800,
      price_per_day: 10800,
      capacity: 15,
      tags: ['Urban', 'Industrial', 'Modern'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Shkodra_Mask Factory.jpg',
      images: ['/locations/mask-factory/photo-1.jpg', '/locations/mask-factory/photo-2.jpg', '/locations/mask-factory/photo-3.jpg', '/locations/mask-factory/photo-4.jpg', '/locations/mask-factory/photo-5.jpg', '/locations/mask-factory/photo-6.jpg', '/locations/mask-factory/photo-7.jpg', '/locations/mask-factory/photo-8.jpg', '/locations/mask-factory/photo-9.jpg', '/locations/mask-factory/photo-10.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '64af5eb2-7617-44ae-8f5a-be83c21dfa6c',
      name: 'Rozafa Castle',
      description: 'Authentic Albanian filming location in Shkodër. Historic Castle perfect for film and photo productions.',
      location_type: 'Historic Castles',
      city: 'Shkodër',
      county: 'Shkodër',
      address: 'Rruga Rozafa, Shkodër',
      latitude: 42.063422,
      longitude: 19.501273,
      price_per_hour: 2500,
      price_per_day: 15000,
      capacity: 25,
      tags: ['Historic', 'Castle', 'Medieval'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Shkodra_Rozafa Castle.jpg',
      images: ['/locations/Shkodra_Rozafa Castle.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'b7b82c4c-4d3f-4468-8254-a9f6f4de0bbc',
      name: 'Fishing Village',
      description: 'Authentic Albanian filming location in Shiroka, Shkodër. Villa/Estate perfect for film and photo productions.',
      location_type: 'Villas & Estates',
      city: 'Shiroka, Shkodër',
      county: 'Shkodër',
      address: 'Rruga Shirokë, Shkodër',
      latitude: 42.085768,
      longitude: 19.448866,
      price_per_hour: 2000,
      price_per_day: 12000,
      capacity: 15,
      tags: ['Luxury', 'Residential', 'Garden'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Shkodra_Shiroka_Fishing Village.jpg',
      images: ['/locations/Shkodra_Shiroka_Fishing Village.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '9c2e2a9a-eebf-4f5c-9a5a-f05119e21fb3',
      name: 'Old Center',
      description: 'Authentic Albanian filming location in Shkodër. Unique Location perfect for film and photo productions.',
      location_type: 'Unique Spaces',
      city: 'Shkodër',
      county: 'Shkodër',
      address: 'Rruga Kolë Idromeno, Shkodër',
      latitude: 42.069189,
      longitude: 19.507726,
      price_per_hour: 1200,
      price_per_day: 7200,
      capacity: 100,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Shkora_Old Center.jpg',
      images: ['/locations/Shkora_Old Center.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'c7d14321-220d-43dd-97c4-b7451a336d33',
      name: 'Agimi Art Center',
      description: 'Authentic Albanian filming location in Tirana. Museum/Gallery perfect for film and photo productions.',
      location_type: 'Cultural Venues',
      city: 'Tirana',
      county: 'Tirana',
      address: 'Bulevardi Bajram Curri, Tirana 1001',
      latitude: 41.325348,
      longitude: 19.814784,
      price_per_hour: 1950,
      price_per_day: 11700,
      capacity: 20,
      tags: ['Cultural', 'Art', 'Educational'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Tirana_Agimi Art Center.jpg',
      images: ['/locations/agimi-art-center/photo-1.jpg', '/locations/agimi-art-center/photo-2.jpg', '/locations/agimi-art-center/photo-3.jpg', '/locations/agimi-art-center/photo-4.jpg', '/locations/agimi-art-center/photo-5.jpg', '/locations/agimi-art-center/photo-6.jpg', '/locations/agimi-art-center/photo-7.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '22dbe5fa-3cf8-4bbb-95e7-57aa575ae115',
      name: 'Bujtina e Diellit',
      description: 'Authentic Albanian filming location in Baldushk, Tirana. Hotel/Guesthouse perfect for film and photo productions.',
      location_type: 'Hotels & Guesthouses',
      city: 'Baldushk, Tirana',
      county: 'Tirana',
      address: 'Rruga e Baldushkut, Fshati Baldushk, Tirana',
      latitude: 41.286675,
      longitude: 19.899872,
      price_per_hour: 1560,
      price_per_day: 9360,
      capacity: 75,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Tirana_Baldushk_Bujtina e Diellit.jpg',
      images: ['/locations/Tirana_Baldushk_Bujtina e Diellit.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'c95f3583-3273-4c6b-a255-c3e6236889e8',
      name: 'Charm Antique Apartment',
      description: 'Authentic Albanian filming location in Tirana. Villa/Estate perfect for film and photo productions.',
      location_type: 'Villas & Estates',
      city: 'Tirana',
      county: 'Tirana',
      address: 'Rruga Kongresi i Tiranës 8, Tirana',
      latitude: 41.32331,
      longitude: 19.819577,
      price_per_hour: 2600,
      price_per_day: 15600,
      capacity: 15,
      tags: ['Luxury', 'Residential', 'Garden'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Tirana_Charm Antique Apartment.jpg',
      images: ['/locations/charm-antique-apartment/photo-1.jpg', '/locations/charm-antique-apartment/photo-2.jpg', '/locations/charm-antique-apartment/photo-3.jpg', '/locations/charm-antique-apartment/photo-4.jpg', '/locations/charm-antique-apartment/photo-5.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '8951153a-a950-4cc0-94fd-c133fd196eac',
      name: 'Chatolic Church',
      description: 'Authentic Albanian filming location in Tirana. Religious Site perfect for film and photo productions.',
      location_type: 'Religious Sites',
      city: 'Tirana',
      county: 'Tirana',
      address: 'Katedralja e Shën Palit, Bulevardi Zhan d\'Ark, Tirana',
      latitude: 41.327731,
      longitude: 19.819319,
      price_per_hour: 1950,
      price_per_day: 11700,
      capacity: 15,
      tags: ['Historic', 'Religious', 'Architecture'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Tirana_Catholic Church.jpg',
      images: ['/locations/catholic-church/photo-1.jpg', '/locations/catholic-church/photo-2.jpg', '/locations/catholic-church/photo-3.jpg', '/locations/catholic-church/photo-4.jpg', '/locations/catholic-church/photo-5.jpg', '/locations/catholic-church/photo-6.jpg', '/locations/catholic-church/photo-7.jpg', '/locations/catholic-church/photo-8.jpg', '/locations/catholic-church/photo-9.jpg', '/locations/catholic-church/photo-10.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '13c16f61-6eca-4894-ab3a-d7363c7fb167',
      name: 'Pug lake',
      description: 'Authentic Albanian filming location in Dajti mountain, Tirana. Waterfront perfect for film and photo productions.',
      location_type: 'Waterfront & Lakes',
      city: 'Dajti mountain, Tirana',
      county: 'Tirana',
      address: 'Parku Kombëtar i Dajtit, Tirana',
      latitude: 41.368465,
      longitude: 19.932073,
      price_per_hour: 1950,
      price_per_day: 11700,
      capacity: 30,
      tags: ['Coastal', 'Water', 'Scenic', 'Beach'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Tirana_Dajti mountain_Pug lake.png',
      images: ['/locations/Tirana_Dajti mountain_Pug lake.png'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '18d9e02f-8dcd-4300-9a81-ffe92ae99594',
      name: 'New bazar',
      description: 'Authentic Albanian filming location in Tirana. Market/Bazaar perfect for film and photo productions.',
      location_type: 'Markets & Bazaars',
      city: 'Tirana',
      county: 'Tirana',
      address: 'Sheshi Avni Rustemi (Pazari i Ri), Tirana',
      latitude: 41.326625,
      longitude: 19.822438,
      price_per_hour: 1560,
      price_per_day: 9360,
      capacity: 15,
      tags: ['Historic', 'Urban', 'Cultural'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Tirana_New bazar.png',
      images: ['/locations/Tirana_New bazar.png'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '97081627-aac8-430c-9e70-3aebc8156d9a',
      name: 'Oda',
      description: 'Authentic Albanian filming location in Tirana. Unique Location perfect for film and photo productions.',
      location_type: 'Unique Spaces',
      city: 'Tirana',
      county: 'Tirana',
      address: 'Rruga Riza Jasa, Tirana 1008',
      latitude: 41.32998,
      longitude: 19.816308,
      price_per_hour: 1560,
      price_per_day: 9360,
      capacity: 30,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Tirana_Oda.jpg',
      images: ['/locations/oda/photo-1.jpg', '/locations/oda/photo-2.jpg', '/locations/oda/photo-3.jpg', '/locations/oda/photo-4.jpg', '/locations/oda/photo-5.jpg', '/locations/oda/photo-6.jpg', '/locations/oda/photo-7.jpg', '/locations/oda/photo-8.jpg', '/locations/oda/photo-9.jpg', '/locations/oda/photo-10.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '32a5735e-ee6c-4aa7-9299-8d138de39b9b',
      name: 'Parking',
      description: 'Authentic Albanian filming location in Tirana. Park/Garden perfect for film and photo productions.',
      location_type: 'Parks & Gardens',
      city: 'Tirana',
      county: 'Tirana',
      address: 'Tirana City Center (Near Skanderbeg Square), Tirana',
      latitude: 41.324796,
      longitude: 19.819596,
      price_per_hour: 1300,
      price_per_day: 7800,
      capacity: 15,
      tags: ['Nature', 'Outdoor', 'Park'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Tirana_Parking.jpg',
      images: ['/locations/Tirana_Parking.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '995ef994-df5a-499d-8c9e-2ae291f8eb34',
      name: 'Polythechnic University',
      description: 'Authentic Albanian filming location in Tirana. Educational Institution perfect for film and photo productions.',
      location_type: 'Cultural Venues',
      city: 'Tirana',
      county: 'Tirana',
      address: 'Sheshi Nënë Tereza, Tirana',
      latitude: 41.325233,
      longitude: 19.815874,
      price_per_hour: 2080,
      price_per_day: 12480,
      capacity: 20,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Tirana_Polythechnic University.jpg',
      images: ['/locations/Tirana_Polythechnic University.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '7f58b944-3051-4bf6-8da0-4ddbed688bb9',
      name: 'Pyramid',
      description: 'Authentic Albanian filming location in Tirana. Monument/Memorial perfect for film and photo productions.',
      location_type: 'Unique Spaces',
      city: 'Tirana',
      county: 'Tirana',
      address: 'Bulevardi Dëshmorët e Kombit, Tirana',
      latitude: 41.322774,
      longitude: 19.819019,
      price_per_hour: 1300,
      price_per_day: 7800,
      capacity: 50,
      tags: ['Historic', 'Monument', 'Cultural'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Tirana_Pyramid.png',
      images: ['/locations/pyramid/photo-1.png', '/locations/pyramid/photo-2.png', '/locations/pyramid/photo-3.png', '/locations/pyramid/photo-4.png'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '48e87c2b-fb79-44f0-b965-af15db54afa6',
      name: 'Shije Fshati',
      description: 'Authentic Albanian filming location in Tirana. Village/Rural perfect for film and photo productions.',
      location_type: 'Unique Spaces',
      city: 'Tirana',
      county: 'Tirana',
      address: 'Rruga e Dibrës 61, Tirana',
      latitude: 41.331153,
      longitude: 19.815096,
      price_per_hour: 1040,
      price_per_day: 6240,
      capacity: 75,
      tags: ['Rural', 'Nature', 'Authentic'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Tirana_Shije Fshati.jpg',
      images: ['/locations/Tirana_Shije Fshati.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '913de376-d954-448d-9f99-306414ec5c34',
      name: 'Under the bridge',
      description: 'Authentic Albanian filming location in Shkoze, Tirana. Bridge/Infrastructure perfect for film and photo productions.',
      location_type: 'Bridges',
      city: 'Shkoze, Tirana',
      county: 'Tirana',
      address: 'Ura e Shkozës, Rruga Ali Demi, Tirana',
      latitude: 41.346819,
      longitude: 19.779656,
      price_per_hour: 1040,
      price_per_day: 6240,
      capacity: 25,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Tirana_Shkoze_Under the bridge.png',
      images: ['/locations/Tirana_Shkoze_Under the bridge.png'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'bc71fa44-28e0-4f0d-98f0-ab338574ab2e',
      name: 'Tea Room',
      description: 'Authentic Albanian filming location in Tirana. Restaurant/Cafe perfect for film and photo productions.',
      location_type: 'Unique Spaces',
      city: 'Tirana',
      county: 'Tirana',
      address: 'Rruga Pjetër Bogdani, Blloku, Tirana',
      latitude: 41.326129,
      longitude: 19.820321,
      price_per_hour: 1820,
      price_per_day: 10920,
      capacity: 75,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Tirana_Tea Room.jpg',
      images: ['/locations/Tirana_Tea Room.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '0bde1c95-bcce-4431-8ded-ef5c4290fd0d',
      name: 'Castle Bazar',
      description: 'Authentic Albanian filming location in Toptani, Tirana. Historic Castle perfect for film and photo productions.',
      location_type: 'Historic Castles',
      city: 'Toptani, Tirana',
      county: 'Tirana',
      address: 'Kalaja e Tiranës, Shëtitorja Murat Toptani, Tirana',
      latitude: 41.332493,
      longitude: 19.820731,
      price_per_hour: 3250,
      price_per_day: 19500,
      capacity: 50,
      tags: ['Historic', 'Castle', 'Medieval'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Tirana_Toptani_Castle_Bazar.png',
      images: ['/locations/toptani-castle/photo-1.png', '/locations/toptani-castle/photo-2.png', '/locations/toptani-castle/photo-3.png', '/locations/toptani-castle/photo-4.png'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '4318ed6a-c2b5-41b6-8d04-9f06b56ddb0a',
      name: 'Vila 15',
      description: 'Authentic Albanian filming location in Tirana. Villa/Estate perfect for film and photo productions.',
      location_type: 'Villas & Estates',
      city: 'Tirana',
      county: 'Tirana',
      address: 'Rruga Sami Frashëri, Tirana',
      latitude: 41.325915,
      longitude: 19.81735,
      price_per_hour: 2600,
      price_per_day: 15600,
      capacity: 40,
      tags: ['Luxury', 'Residential', 'Garden'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Tirana_Vila 15.jpg',
      images: ['/locations/Tirana_Vila 15.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '61c8b386-cf44-43d4-985e-5b2fdd67785c',
      name: 'Zhaku Tatoo Studio',
      description: 'Authentic Albanian filming location in Tirana. Unique Location perfect for film and photo productions.',
      location_type: 'Unique Spaces',
      city: 'Tirana',
      county: 'Tirana',
      address: 'Rruga Myslym Shyri, Tirana',
      latitude: 41.327364,
      longitude: 19.817158,
      price_per_hour: 1560,
      price_per_day: 9360,
      capacity: 40,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Tirana_Zhaku Tatoo Studio.jpg',
      images: ['/locations/Tirana_Zhaku Tatoo Studio.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '93f44577-4599-4b96-80cc-2be6931a8581',
      name: 'Zoo',
      description: 'Authentic Albanian filming location in Tirana. Unique Location perfect for film and photo productions.',
      location_type: 'Unique Spaces',
      city: 'Tirana',
      county: 'Tirana',
      address: 'Rruga e Kopshtit Zoologjik (Near Grand Park), Tirana',
      latitude: 41.329155,
      longitude: 19.823362,
      price_per_hour: 1560,
      price_per_day: 9360,
      capacity: 25,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Tirana_Zoo.jpg',
      images: ['/locations/Tirana_Zoo.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'b5596203-41b8-45aa-9f07-14afc1def5aa',
      name: 'Vila 9',
      description: 'Authentic Albanian filming location in Tirana. Villa/Estate perfect for film and photo productions.',
      location_type: 'Villas & Estates',
      city: 'Tirana',
      county: 'Tirana',
      address: 'Rruga \"Vila 9\", Sauk, Tirana',
      latitude: 41.323326,
      longitude: 19.819713,
      price_per_hour: 2600,
      price_per_day: 15600,
      capacity: 15,
      tags: ['Luxury', 'Residential', 'Garden'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Tirane_Vila 9.jpg',
      images: ['/locations/Tirane_Vila 9.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '5735316c-a78b-4df7-895c-f1bb85e8b6fe',
      name: 'Ottoman bridge',
      description: 'Authentic Albanian filming location in Brataj village, Vlorë. Bridge/Infrastructure perfect for film and photo productions.',
      location_type: 'Bridges',
      city: 'Brataj village, Vlorë',
      county: 'Vlorë',
      address: 'Ura e Bratajt, Fshati Brataj, Vlorë',
      latitude: 40.470178,
      longitude: 19.491446,
      price_per_hour: 960,
      price_per_day: 5760,
      capacity: 75,
      tags: ['Unique', 'Albanian', 'Ottoman'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Vlora_Brataj village_Ottoman bridge.jpg',
      images: ['/locations/Vlora_Brataj village_Ottoman bridge.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '4c62c4d3-c92b-4ccc-8cb9-d2a7b3168846',
      name: 'Fishing Harbour',
      description: 'Authentic Albanian filming location in Vlorë. Waterfront perfect for film and photo productions.',
      location_type: 'Waterfront & Lakes',
      city: 'Vlorë',
      county: 'Vlorë',
      address: 'Porti i Peshkimit (Triport), Vlorë',
      latitude: 40.469633,
      longitude: 19.492326,
      price_per_hour: 1800,
      price_per_day: 10800,
      capacity: 75,
      tags: ['Coastal', 'Water', 'Scenic'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Vlora_Fishing Harbour.jpg',
      images: ['/locations/Vlora_Old Center.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '2d38a720-1e3f-40f8-bd78-fe0a72026ad9',
      name: 'Kanina Castle',
      description: 'Authentic Albanian filming location in Kanina Village, Vlorë. Historic Castle perfect for film and photo productions.',
      location_type: 'Historic Castles',
      city: 'Kanina Village, Vlorë',
      county: 'Vlorë',
      address: 'Kalaja e Kaninës, Fshati Kaninë, Vlorë',
      latitude: 40.468712,
      longitude: 19.488627,
      price_per_hour: 3000,
      price_per_day: 18000,
      capacity: 75,
      tags: ['Historic', 'Castle', 'Medieval'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Vlora_Kanina Village_Kanina Castle.png',
      images: ['/locations/Vlora_Kanina Village_Kanina Castle.png'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '2500877e-9620-4e9d-8b2c-65fb1c5774fb',
      name: 'Bridge',
      description: 'Authentic Albanian filming location in Lapardha village, Vlorë. Bridge/Infrastructure perfect for film and photo productions.',
      location_type: 'Bridges',
      city: 'Lapardha village, Vlorë',
      county: 'Vlorë',
      address: 'Ura e Lapardhasë, Fshati Lapardha, Vlorë',
      latitude: 40.467637,
      longitude: 19.495826,
      price_per_hour: 960,
      price_per_day: 5760,
      capacity: 15,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Vlora_Lapardha village_Bridge.jpg',
      images: ['/locations/Vlora_Lapardha village_Bridge.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'c9cf8cdf-eff0-4825-aede-42e7c2146dcd',
      name: 'Martyrs Cemetery',
      description: 'Authentic Albanian filming location in Vlorë. Monument/Memorial perfect for film and photo productions.',
      location_type: 'Unique Spaces',
      city: 'Vlorë',
      county: 'Vlorë',
      address: 'Rruga 4 Heronjtë (Varrezat e Dëshmorëve), Vlorë',
      latitude: 40.465845,
      longitude: 19.489148,
      price_per_hour: 1200,
      price_per_day: 7200,
      capacity: 30,
      tags: ['Historic', 'Monument', 'Cultural'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Vlora_Martyrs Cemetery.jpg',
      images: ['/locations/Vlora_Martyrs Cemetery.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '5fb3d80e-95bf-48f6-8a4e-25f0b7469515',
      name: 'abandonded stadium',
      description: 'Authentic Albanian filming location in Narte village, Vlorë. Sports Facility perfect for film and photo productions.',
      location_type: 'Sports Facilities',
      city: 'Narte village, Vlorë',
      county: 'Vlorë',
      address: 'Ish-Aerodromi Ushtarak, Fshati Nartë, Vlorë',
      latitude: 40.467154,
      longitude: 19.496246,
      price_per_hour: 2160,
      price_per_day: 12960,
      capacity: 75,
      tags: ['Modern', 'Sports', 'Events'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Vlora_Narte village_abandonded stadium.jpg',
      images: ['/locations/Vlora_Narte village_abandonded stadium.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '9a25ebe0-91ac-420a-8509-4752d88cad5f',
      name: 'Train Tracks',
      description: 'Authentic Albanian filming location in Narte village, Vlorë. Transportation Hub perfect for film and photo productions.',
      location_type: 'Unique Spaces',
      city: 'Narte village, Vlorë',
      county: 'Vlorë',
      address: 'Fshati Nartë (Near Salt Pans), Vlorë',
      latitude: 40.465284,
      longitude: 19.488719,
      price_per_hour: 1080,
      price_per_day: 6480,
      capacity: 25,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Vlora_Narte village_Train Tracks.jpg',
      images: ['/locations/Vlora_Narte village_Train Tracks.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'a0dd1ef7-07c2-47d0-a7d5-c5cf5717b459',
      name: 'Old Center',
      description: 'Authentic Albanian filming location in Vlorë. Unique Location perfect for film and photo productions.',
      location_type: 'Unique Spaces',
      city: 'Vlorë',
      county: 'Vlorë',
      address: 'Rruga Justin Godard (Lagjja Muradie), Vlorë',
      latitude: 40.466489,
      longitude: 19.495826,
      price_per_hour: 1440,
      price_per_day: 8640,
      capacity: 100,
      tags: ['Unique', 'Albanian'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Vlora_Old Center.jpg',
      images: ['/locations/Vlora_Old Center.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '52ba5925-3796-4d9c-87b7-04c4890b4d7d',
      name: 'Park and Playground',
      description: 'Authentic Albanian filming location in Vlorë. Park/Garden perfect for film and photo productions.',
      location_type: 'Parks & Gardens',
      city: 'Vlorë',
      county: 'Vlorë',
      address: 'Lungomare (Near Pavarësia Square), Vlorë',
      latitude: 40.462385,
      longitude: 19.48756,
      price_per_hour: 1200,
      price_per_day: 7200,
      capacity: 100,
      tags: ['Nature', 'Outdoor', 'Park'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Vlora_Park and Playground.jpg',
      images: ['/locations/Vlora_Park and Playground.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '8f89c578-ef98-49ee-864f-f699eaf9469d',
      name: 'Pine Forest',
      description: 'Authentic Albanian filming location in Vlorë. Park/Garden perfect for film and photo productions.',
      location_type: 'Parks & Gardens',
      city: 'Vlorë',
      county: 'Vlorë',
      address: 'Pylli i Sodës, Vlorë',
      latitude: 40.467339,
      longitude: 19.494722,
      price_per_hour: 1200,
      price_per_day: 7200,
      capacity: 100,
      tags: ['Nature', 'Outdoor', 'Park'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Vlora_Pine Forest.jpg',
      images: ['/locations/pine-forest/photo-1.jpg', '/locations/pine-forest/photo-2.jpg', '/locations/pine-forest/photo-3.jpg', '/locations/pine-forest/photo-4.jpg', '/locations/pine-forest/photo-5.jpg', '/locations/pine-forest/photo-6.jpg', '/locations/pine-forest/photo-7.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '984adf75-c88f-451f-b2cc-69f1422c37eb',
      name: 'Promenade',
      description: 'Authentic Albanian filming location in Vlorë. Waterfront perfect for film and photo productions.',
      location_type: 'Waterfront & Lakes',
      city: 'Vlorë',
      county: 'Vlorë',
      address: 'Lungomare, Rruga Sazani, Vlorë',
      latitude: 40.464388,
      longitude: 19.495994,
      price_per_hour: 1800,
      price_per_day: 10800,
      capacity: 50,
      tags: ['Coastal', 'Water', 'Scenic'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Vlora_Promenade.jpg',
      images: ['/locations/Vlora_Promenade.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: 'abd965c7-54ce-4041-b28e-4597bd473e44',
      name: 'Old monastery',
      description: 'Authentic Albanian filming location in Sevaster village, Vlorë. Religious Site perfect for film and photo productions.',
      location_type: 'Religious Sites',
      city: 'Sevaster village, Vlorë',
      county: 'Vlorë',
      address: 'Manastiri i Shën Mërisë, Fshati Sevaster, Vlorë',
      latitude: 40.470519,
      longitude: 19.491877,
      price_per_hour: 1800,
      price_per_day: 10800,
      capacity: 30,
      tags: ['Historic', 'Religious', 'Architecture'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Vlora_Sevaster village_Old monastery.jpg',
      images: ['/locations/Vlora_Sevaster village_Old monastery.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '32cfebd6-ba86-465b-a83b-36c8e1f09a82',
      name: 'Sport Courts',
      description: 'Authentic Albanian filming location in Vlorë. Sports Facility perfect for film and photo productions.',
      location_type: 'Sports Facilities',
      city: 'Vlorë',
      county: 'Vlorë',
      address: 'Lungomare Sport Complex, Vlorë',
      latitude: 40.46154,
      longitude: 19.496075,
      price_per_hour: 2160,
      price_per_day: 12960,
      capacity: 100,
      tags: ['Modern', 'Sports', 'Events'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Vlora_Sport Courts.jpg',
      images: ['/locations/Vlora_Sport Courts.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '90eb6ff8-c63d-41a0-9f97-37331f90f91f',
      name: 'Orthodox Monastery',
      description: 'Authentic Albanian filming location in Zvernec, Vlorë. Religious Site perfect for film and photo productions.',
      location_type: 'Religious Sites',
      city: 'Zvernec, Vlorë',
      county: 'Vlorë',
      address: 'Ishulli i Zvërnecit, Narta Lagoon, Vlorë',
      latitude: 40.469369,
      longitude: 19.487588,
      price_per_hour: 1800,
      price_per_day: 10800,
      capacity: 40,
      tags: ['Historic', 'Religious', 'Architecture'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Vlora_Zvernec_Orthodox Monastery.jpg',
      images: ['/locations/orthodox-monastery/photo-1.jpg', '/locations/orthodox-monastery/photo-2.jpg', '/locations/orthodox-monastery/photo-3.jpg', '/locations/orthodox-monastery/photo-4.jpg', '/locations/orthodox-monastery/photo-5.jpg', '/locations/orthodox-monastery/photo-6.jpg', '/locations/orthodox-monastery/photo-7.jpg', '/locations/orthodox-monastery/photo-8.jpg', '/locations/orthodox-monastery/photo-9.jpg', '/locations/orthodox-monastery/photo-10.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  },
  {
      id: '0b056bc1-0103-4d7e-ae0f-54b41a13a78a',
      name: 'Old Beach House',
      description: 'Authentic Albanian filming location in Vlorë. Villa/Estate perfect for film and photo productions.',
      location_type: 'Villas & Estates',
      city: 'Vlorë',
      county: 'Vlorë',
      address: 'Plazhi i Vjetër, Vlorë',
      latitude: 40.461173,
      longitude: 19.494998,
      price_per_hour: 2400,
      price_per_day: 14400,
      capacity: 15,
      tags: ['Luxury', 'Residential', 'Garden', 'Beach'],
      amenities: ['Parking', 'Electricity', 'Natural Light', 'Easy Access'],
      cover_image: '/locations/Vlore╠ê_Old Beach House.jpg',
      images: ['/locations/Vlore╠ê_Old Beach House.jpg'],
      available: true,
      host_name: 'Skauter Team',
      'host_verified': true,
  }
]


locations.each do |attrs|
  location = Location.find_or_initialize_by(id: attrs[:id])
  location.assign_attributes(attrs)
  location.save!
end

puts "✅ Seeded #{locations.size} locations"
